const data = [
  {
    t_id: "1",
    alevel: 0,
    parent_id: 0,
    t_label: "худуд1",
    id: 1,
    label: "Ўзбекистон",
    parent_label: null,
  },
  {
    t_id: "2",
    alevel: 1,
    parent_id: 1,
    t_label: "худуд2",
    id: 2,
    label: "Сурхондарё",
    parent_label: "Ўзбекистон",
  },
  {
    t_id: "3",
    alevel: 1,
    parent_id: 2,
    t_label: "худуд3",
    id: 3,
    label: "Денов тумани",
    parent_label: "Сурхондарё",
  },
  {
    t_id: "37",
    alevel: 0,
    parent_id: 0,
    t_label: "Тадбир",
    id: 4,
    label: "Низога тадбир",
    parent_label: null,
  },
  {
    t_id: "40",
    alevel: 3,
    parent_id: 25,
    t_label: "мулоқот",
    id: 5,
    label: "профилактик суҳбат",
    parent_label: "Мулоқот",
  },
  {
    t_id: "40",
    alevel: 3,
    parent_id: 25,
    t_label: "мулоқот",
    id: 6,
    label: "тушунтириш",
    parent_label: "Мулоқот",
  },
  {
    t_id: "40",
    alevel: 3,
    parent_id: 25,
    t_label: "мулоқот",
    id: 7,
    label: "огоҳлантриш",
    parent_label: "Мулоқот",
  },
  {
    t_id: "40",
    alevel: 3,
    parent_id: 25,
    t_label: "мулоқот",
    id: 8,
    label: "муҳокама қилиш (МФЙда)",
    parent_label: "Мулоқот",
  },
  {
    t_id: "45",
    alevel: 1,
    parent_id: 4,
    t_label: "ёрдам",
    id: 9,
    label: "ёрдам (амалий )",
    parent_label: "Низога тадбир",
  },
  {
    t_id: "45",
    alevel: 3,
    parent_id: 4,
    t_label: "ёрдам",
    id: 10,
    label: "ёрдам (моддий)",
    parent_label: "Низога тадбир",
  },
  {
    t_id: "45",
    alevel: 4,
    parent_id: 9,
    t_label: "ёрдам",
    id: 11,
    label: "ишга жойлаштириш (ихтиёрий)",
    parent_label: "ёрдам (амалий )",
  },
  {
    t_id: "45",
    alevel: 4,
    parent_id: 9,
    t_label: "ёрдам",
    id: 12,
    label: "ишга жойлаштириш (мажбурий)",
    parent_label: "ёрдам (амалий )",
  },
  {
    t_id: "46",
    alevel: 4,
    parent_id: 19,
    t_label: "даволаш",
    id: 13,
    label: "даволанишга юбориш (мажбурий)",
    parent_label: "даволанишга юбориш ",
  },
  {
    t_id: "46",
    alevel: 4,
    parent_id: 19,
    t_label: "даволаш",
    id: 14,
    label: "даволанишга юбориш (ихтиёрий)",
    parent_label: "даволанишга юбориш ",
  },
];

export default data;
